#!/bin/bash -ex
export RBENV_ROOT=/opt/altiscale/rbenv
export PATH="$RBENV_ROOT/bin:$PATH"

# mock munges this symlink
(cd $RBENV_ROOT/bin ; ln -sf ../libexec/rbenv rbenv)

eval "$(rbenv init -)"
for RUBY in $@ ; do
    rbenv install $RUBY --verbose
    rbenv shell $RUBY
    gem install bundler
    rbenv shell --unset
done 
